# Generated by Django 4.2.13 on 2024-06-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_appointment_waiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Consultation Notes'),
        ),
    ]
