# Generated by Django 4.2.13 on 2024-07-04 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_patientrecord_patientnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='waiver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.waiver'),
        ),
    ]
