# Generated by Django 4.2.13 on 2024-07-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_alter_appointment_waiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='waiver',
            field=models.TextField(null=True),
        ),
    ]
