# Generated by Django 4.2.13 on 2024-07-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_alter_appointment_waiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientnote',
            name='image',
            field=models.ImageField(null=True, upload_to='patient_notes/'),
        ),
    ]
